# Generated by Django 5.2.6 on 2026-05-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentprofile',
            name='primary_skill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='professional_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
