# Generated by Django 5.2.6 on 2026-09-23 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_talentprofile_primary_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='last_reminder_sent_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='reminder_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='reminder_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='reminder_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('weekends', 'Weekends only')], default='daily', max_length=10),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='reminder_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='reminder_timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='reminder_weekday',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
