# Generated by Django 5.2.6 on 2026-09-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_reminder_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
