# Generated by Django 5.2.6 on 2025-12-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_creatorprofile_user_alter_talentprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
