# Generated by Django 5.2.6 on 2025-12-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_creatorprofile_avatar_creatorprofile_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='availability',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
