# Generated by Django 5.2.6 on 2026-01-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_talentprofile_availability_talentprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
