# Generated by Django 5.2.6 on 2026-01-25 15:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_creatorprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_picture'),
        ),
    ]
