# Generated by Django 5.2.6 on 2026-01-25 16:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_creatorprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_picture'),
        ),
    ]
