# Generated by Django 5.2.6 on 2026-03-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('creator', 'Creator'), ('talent', 'Talent'), ('client', 'Client')], max_length=10),
        ),
    ]
