# Generated by Django 5.2.6 on 2026-09-17 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_crmcolumn_url_field_type'),
        ('library', '0003_document_is_favorite_alter_document_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmsheet',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_sheets', to='library.folder'),
        ),
        migrations.AddField(
            model_name='crmsheet',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
