# Generated by Django 5.2.6 on 2026-07-01 08:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_alter_onboardinginstance_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_index', models.PositiveIntegerField(blank=True, null=True)),
                ('file', models.FileField(upload_to='onboarding_uploads/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='onboarding.onboardinginstance')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
