# Generated by Django 5.2.6 on 2026-07-16 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_onboardingupload'),
        ('project', '0008_task_awaiting_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingtemplate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_templates', to='project.project'),
        ),
    ]
