# Generated by Django 5.2.6 on 2025-12-18 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_project_updated_at_project_completed_tasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='completed_tasks',
        ),
        migrations.RemoveField(
            model_name='project',
            name='task_count',
        ),
    ]
