# Generated by Django 5.2.6 on 2026-07-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_task_multi_assignees'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='awaiting_approval',
            field=models.BooleanField(default=False),
        ),
    ]
