# Generated by Django 5.2.6 on 2026-08-19 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_groupmessage_edited_at_groupmessage_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='project.taskcomment'),
        ),
    ]
