# Generated by Django 5.2.6 on 2026-08-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_taskcomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allow_talent_task_creation',
            field=models.BooleanField(default=False),
        ),
    ]
