# Generated by Django 5.2.6 on 2026-08-31 01:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_project_allow_talent_task_creation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_task_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
