# Generated by Django 5.2.6 on 2026-09-26 11:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_personaltask'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTaskAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='personal_task_attachments/')),
                ('url', models.URLField(blank=True, max_length=2048, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='project.personaltask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
