# Generated by Django 5.2.6 on 2026-05-05 09:10

import django.db.models.deletion
import portal.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, default=portal.models._generate_invite_token, max_length=64, unique=True)),
                ('client_email', models.EmailField(max_length=254)),
                ('onboarding_form', models.JSONField(blank=True, default=dict)),
                ('responses', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invites', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_invites', to='project.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'client_email')},
            },
        ),
    ]
